default: error
logs:
  gsp: critical
  root: error
  openzwave: error
  libopenzwave: error
  py.warnings: error
  aiohttp.server: critical
  homeassistant.setup: error
  homeassistant.core: critical
  homeassistant.exceptions: error
  homeassistant.helpers.script: error  
  homeassistant.helpers.entity: critical
  homeassistant.components.http: error
  homeassistant.components.zwave: error
  homeassistant.components.sensor: critical
  homeassistant.components.recorder: error
  homeassistant.components.discovery: error
  homeassistant.components.automation: error
  homeassistant.components.climate.nest: error
  homeassistant.components.media_player: error
  homeassistant.components.device_tracker: error
  custom_components.media_player.sharptv: error
  homeassistant.components.emulated_hue: error
  homeassistant.components.camera.generic: critical
