input_label:
  set_value:
    description: Use this service to set or update value of input label
    fields:
      entity_id:
        description: Entity id of the input label
        example: 'input.label.some_string'
      value:
        description: String value you want to set
        example: "Hello, Home Assistant!"
