global_variable_int:
  set_value:
    description: Use this service to set or update value of global integer variable
    fields:
      entity_id:
        description: Entity id of the global integer variable
        example: 'global_variable_int.some_number'
      value:
        description: Value you want to set
        example: '1234'
