###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Evening
#   @description    :   Evening Routines
###############################################################################
homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'evening'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

automation:
###############################################################################
# Turn outdoor lights on 15 minutes before sunset
###############################################################################
  - alias: Evening Outdoor Lights ON (At Sunset)
    initial_state: true
    hide_entity: true
    trigger:
      platform: sun
      event: sunset
      offset: '+00:00:00'
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.wemofrontporchlightswitch
      - service: switch.turn_on
        data:
          entity_id: switch.wemobackyardlightswitch
      - service: light.turn_on
        data:
          entity_id: light.tradfri_bulb_e26_ws_opal_980lm

###############################################################################
# Turn indoor lights on 60 minutes before sunset
###############################################################################
  - alias: Evening Indoor Lights ON Before Sunset
    initial_state: true
    hide_entity: true
    trigger:
      platform: sun
      event: sunset
      offset: '-01:00:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.dinette
          transition: 15
          brightness: 255
          color_temp: 155
      - service: light.turn_on
        data:
          entity_id: light.hue_color_lamp_1
          transition: 5
          brightness: 255
          color_temp: 154
      - service: light.turn_on
        data:
          entity_id: light.hue_color_lamp_2
          transition: 5
          brightness: 255
          color_temp: 154
      - service: light.turn_on
        data:
          entity_id: light.hue_color_lamp_3
          transition: 5
          brightness: 255
          color_temp: 154
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_1
          brightness: 10
          color_temp: 366
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_2
          brightness: 10
          color_temp: 366
      - service: switch.turn_on
        entity_id: switch.zwave_smart_switch_switch