###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Evening
#   @description    :   Evening Routines
###############################################################################
homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'evening'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

automation:
###############################################################################
# Turn Home Security System ON at sunset time
###############################################################################
  - alias: Evening Home Security System ON (At Sunset)
    initial_state: true
    hide_entity: true
    trigger:
      platform: sun
      event: sunset
      offset: '+00:00:00'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: alarm_control_panel.simplisafe
        state: 'disarmed'
    action:
      - service: script.voice_notify
        data_template:
          value1: >
            {% if states.binary_sensor.back_door_sensor_sensor.state == "off" and states.binary_sensor.front_door_sensor_sensor.state  == "off" %}
              It's getting dark outside, and your home security system is now set to HOME mode.
            {% else %}
              It's getting dark outside, and your doors are open. Home Security System could not be turned on.
            {% endif %}
      - service_template: >-
          {% if states.binary_sensor.back_door_sensor_sensor.state == "off" and states.binary_sensor.front_door_sensor_sensor.state  == "off" %}
            alarm_control_panel.alarm_arm_home
          {% else %}
            alarm_control_panel.disarm
          {% endif %}
        data:
          entity_id: alarm_control_panel.simplisafe
      - service: script.notify_me
        data_template:
          value1: >
            {% if states.binary_sensor.back_door_sensor_sensor.state == "off" and states.binary_sensor.front_door_sensor_sensor.state  == "off" %}
              It's getting dark outside, and your home security system is now set to HOME mode.
            {% else %}
              It's getting dark outside, and your doors are open. Home Security System could not be turned on.
            {% endif %}
          value2: ""

###############################################################################
# Turn outdoor lights on 15 minutes before sunset
###############################################################################
  - alias: Evening Outdoor Lights ON (At Sunset)
    initial_state: true
    hide_entity: true
    trigger:
      platform: sun
      event: sunset
      offset: '+00:00:00'
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.wemofrontporchlightswitch
      - service: switch.turn_on
        data:
          entity_id: switch.wemobackyardlightswitch
      - service: light.turn_on
        data:
          entity_id: light.tradfri_bulb_e26_ws_opal_980lm
      - service: switch.turn_on
        data:
          entity_id: switch.switch_two

###############################################################################
# Turn indoor lights on 60 minutes before sunset
###############################################################################
  - alias: Evening Indoor Lights ON Before Sunset
    initial_state: true
    hide_entity: true
    trigger:
      platform: sun
      event: sunset
      offset: '-01:00:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.dinette
          transition: 15
          brightness: 255
          color_temp: 155
      - service: light.turn_on
        data:
          entity_id: light.hue_color_lamp_1
          transition: 5
          brightness: 255
          color_temp: 154
      - service: light.turn_on
        data:
          entity_id: light.hue_color_lamp_2
          transition: 5
          brightness: 255
          color_temp: 154
      - service: light.turn_on
        data:
          entity_id: light.hue_color_lamp_3
          transition: 5
          brightness: 255
          color_temp: 154
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_1
          brightness: 10
          color_temp: 366
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_2
          brightness: 10
          color_temp: 366