# ##############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Random Chuck Norris Facts
#   @description    :   Daily dose of Chuck Norris. 
#                       It is INTENTIONALLY set to query once a day. 
#                       Know your limits, and DO NOT mess with Chuck Norris!
# ##############################################################################
homeassistant:
  customize:
    sensor.fact_of_the_day:
      friendly_name: Fact Of The Day
      icon: mdi:panda
      hidden: true

sensor:
  - platform: rest
    name: fact_of_the_day
    resource: http://api.icndb.com/jokes/random?firstName=Chuck&lastName=Norris&limitTo=[nerdy]
    value_template: '{{ value_json.value.joke }}'
    scan_interval: 86400

automation:

  - alias: New joke At Startup
    initial_state: true
    hide_entity: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay:
          seconds: 15
      - service: persistent_notification.create
        data:
          title: 'Chuck Norris fact:'
          message: '{{ states.sensor.fact_of_the_day.state  }}'