group:
  Xiaomi Products:
    entities:
      - sensor.xiaomi_aqara_human_body_sensor
      - sensor.xiaomi_aqara_temperature_humidity_sensor
      - sensor.xiaomi_door_window_sensor
      - sensor.anycubic_kossel_3d_printer

sensor:
  - platform: gearbest
    currency: USD
    items:
      - url: https://www.gearbest.com/alarm-systems/pp_659226.html
        name: Xiaomi Aqara Human Body Sensor
      - url: https://www.gearbest.com/access-control/pp_626702.html
        name: Xiaomi Aqara Temperature Humidity Sensor
      - url: https://www.gearbest.com/smart-light-bulb/pp_257677.html
        name: Xiaomi Door Window Sensor
      - url: https://www.gearbest.com/3d-printers-3d-printer-kits/pp_1412328.html
        name: Anycubic Kossel 3D Printer