###############################################################################
# @Author:    Suresh Kalavala
# @Date:      09/14/2017
# @Package:   global_vars.yaml
# @Desc:      Global Variable File - defines a bunch of global integer 
#             variables, shows how to update the variables using service
#             The default value is optional, which defaults to 0
###############################################################################

homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'global_vars'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

      not_hidden: &not_hidden
        <<: *customize
        hidden: false
        critical: true

    variable_int.some_int_number1:
      <<: *not_hidden
    variable_int.some_int_number2:
      <<: *not_hidden
    variable_bool.some_bool_flag1:
      <<: *not_hidden
    variable_bool.some_bool_flag2:
      <<: *not_hidden
    variable_float.some_float_number1:
      <<: *not_hidden
    variable_float.some_float_number2:
      <<: *not_hidden
    variable_string.some_string1:
      <<: *not_hidden
    variable_string.some_string2:
      <<: *not_hidden

group:
  My Variables:
    entities:
      - variable_int.some_int_number1
      - variable_int.some_int_number2
      - variable_bool.some_bool_flag1
      - variable_bool.some_bool_flag2
      - variable_float.some_float_number1
      - variable_float.some_float_number2
      - variable_string.some_string1
      - variable_string.some_string2

# INTEGER TYPE VARIABLES
###############################################################################
variable_int:

  some_int_number1:
    name: Some Number 1
    icon: mdi:numeric

  some_int_number2:
    name: Some Number 2
    value: 98765
    readonly: true
    icon: mdi:numeric

# BOOLEAN TYPE VARIABLES
###############################################################################
variable_bool:

  some_bool_flag1:
    name: Some Flag
    value: True
    readonly: true
    icon: mdi:flag

  some_bool_flag2:
    name: Some Flag
    icon: mdi:flag

# FLOAT TYPE VARIABLES
###############################################################################
variable_float:

  some_float_number1:
    name: Some Float
    value: 123.456
    readonly: true
    icon: mdi:water-percent

  some_float_number2:
    name: Some Float 2
    icon: mdi:water-percent

# STRING TYPE VARIABLES
###############################################################################
variable_string:

  some_string1:
    name: Some String 1 
    icon: mdi:alphabetical

  some_string2:
    name: Some String 2
    readonly: true
    value: 'Hello, Home Assistant!'
    icon: mdi:alphabetical

automation:

# This is a sample automation to demonstrate use of global variable in service
# The variable is used as a counter, that keeps track of how many times the 
# light bulb was turned on
###############################################################################
  - alias: Use the variable as a counter
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: light.dinette
      from: 'off'
      to: 'on'
    action:
      - service: variable_int.set_value
        entity_id: variable_int.some_int_number1
        data_template: 
          value: '{{ (states.variable_int.some_int_number1.state | int) + 1 |int }}'