###############################################################################
# @Author:    Suresh Kalavala
# @Date:      09/14/2017
# @Package:   global_vars.yaml
# @Desc:      Global Variable File - defines a bunch of global integer 
#             variables, shows how to update the variables using service
#             The default value is optional, which defaults to 0
###############################################################################

homeassistant:
  customize:

    global_variable_int.some_number1:
      hidden: true
    global_variable_int.some_number2:
      hidden: true

# global "integer" type variables
###############################################################################

# INTEGER TYPE VARIABLES
###############################################################################
global_variable_int:

  some_number1:
    name: Some Number 1
    icon: mdi:numeric

  some_number2:
    name: Some Number 2
    value: 98765
    icon: mdi:numeric

# BOOLEAN TYPE VARIABLES
###############################################################################
global_variable_bool:

  some_flag1:
    name: Some Flag
    value: True

  some_flag2:
    name: Some Flag

# FLOAT TYPE VARIABLES
###############################################################################
global_variable_float:

  some_float_number1:
    name: Some Float
    value: 123.456

  some_float_number2:
    name: Some Float 2

# STRING TYPE VARIABLES
###############################################################################
global_variable_string:

  some_string1:
    name: Some String 1 
    icon: mdi:alphabetical

  some_string2:
    name: Some String 2
    value: 'Hello, Home Assistant!'
    icon: mdi:alphabetical

automation:

# This is a sample automation to demonstrate use of global variable in service
###############################################################################
  - alias: Set random value everytime light state changes
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: light.dinette
    action:
      - service: global_variable_int.set_value
        entity_id: global_variable_int.some_number1
        data_template:
          value: '{{ range(0,10000) | random | int }}'
      - service: global_variable_int.set_value
        entity_id: global_variable_int.some_number2
        data_template:
          value: '{{ range(0,10000) | random | int }}'
