###############################################################################
# @Author:    Suresh Kalavala
# @Date:      09/14/2017
# @Package:   global_vars.yaml
# @Desc:      Global Variable File - defines a bunch of global integer 
#             variables, shows how to update the variables using service
#             The default value is optional, which defaults to 0
###############################################################################

homeassistant:
  customize:

    variable_int.some_int_number1:
      hidden: false
    variable_int.some_int_number2:
      hidden: false
    variable_bool.some_bool_flag1:
      hidden: false
    variable_bool.some_bool_flag2:
      hidden: false
    variable_float.some_float_number1:
      hidden: false
    variable_float.some_float_number2:
      hidden: false
    variable_string.some_string1:
      hidden: false
    variable_string.some_string2:
      hidden: false

group:
  My Variables:
    entities:
      - variable_int.some_int_number1
      - variable_int.some_int_number2
      - variable_bool.some_bool_flag1
      - variable_bool.some_bool_flag2
      - variable_float.some_float_number1
      - variable_float.some_float_number2
      - variable_string.some_string1
      - variable_string.some_string2

# INTEGER TYPE VARIABLES
###############################################################################
variable_int:

  some_int_number1:
    name: Some Number 1
    icon: mdi:numeric

  some_int_number2:
    name: Some Number 2
    value: 98765
    icon: mdi:numeric

# BOOLEAN TYPE VARIABLES
###############################################################################
variable_bool:

  some_bool_flag1:
    name: Some Flag
    value: True
    icon: mdi:flag

  some_bool_flag2:
    name: Some Flag
    icon: mdi:flag

# FLOAT TYPE VARIABLES
###############################################################################
variable_float:

  some_float_number1:
    name: Some Float
    value: 123.456
    icon: mdi:water-percent

  some_float_number2:
    name: Some Float 2
    icon: mdi:water-percent

# STRING TYPE VARIABLES
###############################################################################
variable_string:

  some_string1:
    name: Some String 1 
    icon: mdi:alphabetical

  some_string2:
    name: Some String 2
    value: 'Hello, Home Assistant!'
    icon: mdi:alphabetical

automation:

# This is a sample automation to demonstrate use of global variable in service
###############################################################################
  - alias: Set random value everytime light state changes
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: light.dinette
    action:
      - service: variable_int.set_value
        entity_id: variable_int.some_number1
        data_template:
          value: '{{ range(0,10000) | random | int }}'
      - service: variable_int.set_value
        entity_id: variable_int.some_number2
        data_template:
          value: '{{ range(0,10000) | random | int }}'
