homeassistant:
  customize:
    sensor.suresh_location:
      friendly_name: Suresh's Location
      icon: mdi:map-marker
    sensor.mallika_location:
      friendly_name: Mallika's Location
      icon: mdi:map-marker
    sensor.srinika_location:
      friendly_name: Srinika's Location
      icon: mdi:map-marker
    sensor.hasika_location:
      friendly_name: Hasika's Location
      icon: mdi:map-marker

group:
  Where is everyone:
    entities:
      - sensor.suresh_location
      - sensor.mallika_location
      - sensor.srinika_location
      - sensor.hasika_location

sensor:
  - platform: google_geocode
    name: Suresh Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.suresh_suresh
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Mallika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.mallika_mallika
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Srinika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.srinika_srinika
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Hasika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.hasika_hasika
    options: formatted_address
    display_zone: hide
