###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Home Security 
#   @description    :   Home Security System Sensors and Automations
###############################################################################
homeassistant:
  customize:
  
    group.home_security_system:
      order: 7

    alarm_control_panel.simplisafe:
      friendly_name: Home Security System
      icon: mdi:security
    sensor.my_alarm_control_panel:
      friendly_name: Home Security System
      icon: mdi:security

alarm_control_panel:
  platform: simplisafe
  name: Simplisafe
  username: !secret simplisafe_username
  password: !secret simplisafe_password

group:
  Home Security System:
    entities:
      - alarm_control_panel.simplisafe
      - automation.notify_home_security_status_change
  
automation:

#
# Change Leeo Alert color based on Home Security Status
#
  - alias: Home Security Status Leeo Color
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
    condition:
      - condition: template
        value_template: "{% if trigger.from_state %} True {% else %} False {% endif %}"
      - condition: template
        value_template: '{% if states.alarm_control_panel.simplisafe.state == "unknown" %} False {% else %} True {% endif %}'
      - condition: template
        value_template: '{% if states.alarm_control_panel.simplisafe.state | trim == "" %} False {% else %} True {% endif %}'
    action:
      - service: script.ifttt_leeo_color_change
        data_template:
          value1: >
            {% if states.alarm_control_panel.simplisafe.state == "armed_home" %}
              "#0000FF"
            {% elif states.alarm_control_panel.simplisafe.state == "armed_away" %}
              "#00FF00"
            {% elif states.alarm_control_panel.simplisafe.state == "triggered" %}
              "#FF0000"
            {% elif states.alarm_control_panel.simplisafe.state == "disarmed" %}
              "#FF0000"
            {% endif %}

  - alias: Notify Home Security Status Change
    initial_state: true
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
    condition:
      - condition: template
        value_template: >
          {%- if states.automation.notify_home_security_status_change.attributes.last_triggered -%}
            {{ (as_timestamp(now()) - as_timestamp(states.automation.notify_home_security_status_change.attributes.last_triggered)) > 90 }}
          {%- else -%}
            true
          {%- endif -%}
    action:
      - service: script.notify_me
        data_template:
          value1: >
            {% if states.alarm_control_panel.simplisafe.state == "armed_home" %}
              Your home is now secured!
            {% elif states.alarm_control_panel.simplisafe.state == "armed_away" %}
              Your Home Security System is now set to Away mode!
            {% elif states.alarm_control_panel.simplisafe.state == "triggered" %}
              Attention!: Your Home Security System is triggered! It has been notified to the authorities.
            {% elif states.alarm_control_panel.simplisafe.state == "disarmed" %}
              Attention!: Your Home Security System is turned OFF.
            {% endif %}
          value2: ""
      - service: script.voice_notify
        data_template:
          value1: >
            {% if states.alarm_control_panel.simplisafe.state == "armed_home" %}
              Your home is now secured!
            {% elif states.alarm_control_panel.simplisafe.state == "armed_away" %}
              Your Home Security System is now set to Away mode!
            {% elif states.alarm_control_panel.simplisafe.state == "triggered" %}
              Attention!: Your Home Security System is triggered! It has been notified to the authorities.
            {% elif states.alarm_control_panel.simplisafe.state == "disarmed" %}
              Attention!: Your Home Security System is turned OFF. 
            {% endif %}