################################################################
## Credits to @dale3h
## Package / Homebridge
################################################################

###################################################
## Customize
## Hide all the domains by default from homebridge
###################################################

homeassistant:
  customize_domain:

    binary_sensor:
      homebridge_hidden: true

    climate:
      homebridge_hidden: true

    cover:
      homebridge_hidden: true

    device_tracker:
      homebridge_hidden: true

    fan:
      homebridge_hidden: true

    group:
      homebridge_hidden: true

    input_boolean:
      homebridge_hidden: true

    light:
      homebridge_hidden: true

    lock:
      homebridge_hidden: true

    media_player:
      homebridge_hidden: true

    scene:
      homebridge_hidden: true

    sensor:
      homebridge_hidden: true

    switch:
      homebridge_hidden: true
