homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'http'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

http:
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - 192.168.200.0/24
    - 10.10.1.0/24
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3
