###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Lights
#   @description    :   Lights, Lights, Lights! All the Lights are here!
###############################################################################
homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'lights'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    switch.wemofrontporchlightswitch:
      <<: *exposed
      icon: mdi:lightbulb
      friendly_name: Front Porch Lights
      emulated_hue_name: Front Yard Lights
    switch.wemoswitch1:
      <<: *exposed
      icon: mdi:lamp
      friendly_name: TV Reset
      emulated_hue_name: TV Reset
    switch.wemobackyardlightswitch:
      <<: *exposed
      icon: mdi:lightbulb
      friendly_name: Backyard Lights
      emulated_hue_name: Backyard Lights
    light.tradfri_group:
      <<: *exposed
      friendly_name: IKEA Lights
    light.family_room:
      <<: *exposed
      friendly_name: Family Room Lights
      emulated_hue_name: Family Room Lights
    light.master_bedroom:
      <<: *exposed
      friendly_name: Master Bedroom Lights
      emulated_hue_name: Master Bedroom Lights
    light.dinette:
      <<: *exposed
      friendly_name: Kitchen Light
      emulated_hue_name: Kitchen Light

    light.tradfri_bulb_e26_ws_opal_980lm:
      <<: *exposed
      friendly_name: Office Room Light
      emulated_hue_name: Office Room Light
    
    switch.zwave_smart_switch_switch:
      friendly_name: Office Room Accent Lights

    light.all_hue_lights:
      <<: *hidden

    light.hue_color_lamp_1:
      <<: *not_exposed
      friendly_name: Family Room Light 1
    light.hue_color_lamp_2:
      <<: *not_exposed
      friendly_name: Family Room Light 2
    light.hue_color_lamp_3:
      <<: *not_exposed
      friendly_name: Family Room Light 3
    input_boolean.short_flash:
      <<: *not_exposed
      icon: mdi:flash
      friendly_name: Short Flash
    input_boolean.long_flash:
      <<: *not_exposed
      icon: mdi:flash      
      friendly_name: Long Flash
    input_boolean.animate_downstairs_lights:
      <<: *not_exposed
      icon: mdi:flash-outline
      friendly_name: Animate Family Room Lights    
    input_boolean.animate_upstairs_lights:
      <<: *not_exposed
      icon: mdi:flash-outline
      friendly_name: Animate Master Bedroom Lights

group:
  Upstairs Lights:
    entities:
      - light.master_bedroom_1
      - light.master_bedroom_2
      - light.master_bedroom
      - switch.kids_bedroom
      - switch.guest_bedroom_1
      - switch.guest_bedroom_2

  Downstairs Lights:
    entities:
      - light.family_room
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
      - group.ikea_bulbs
      - light.dinette
      - switch.wemofrontporchlightswitch
      - switch.wemobackyardlightswitch
      - switch.garage_lights
      - light.tradfri_bulb_e26_ws_opal_980lm
      - light.tradfri_group
      - switch.zwave_smart_switch_switch

  Light Automations:
    control: hidden
    entities:
      - automation.animate_master_bedroom_lights
      - input_boolean.animate_kitchen_lights
      - input_boolean.animate_downstairs_lights
      - input_boolean.animate_upstairs_lights
      - input_boolean.short_flash
      - input_boolean.long_flash

light:
  - platform: lifx
    broadcast: !secret lifx_broadcast_ip
  - platform: hue
    host: !secret philips_hue_ipaddress

switch:
  - platform: tplink
    host: !secret tplink_kids_bedroom
    name: Kids Bedroom
  - platform: tplink
    host: !secret tplink_guest_bedroom_1
    name: Guest Bedroom 1
  - platform: tplink
    host: !secret tplink_guest_bedroom_2
    name: Guest Bedroom 2
  - platform: tplink
    host: !secret tplink_garage
    name: Garage Lights
      
# tradfri:
#   host: !secret ikea_gateway_ip
#   api_key: !secret ikea_gateway_security_code
#   allow_tradfri_groups: false

wemo:
  static:
    - !secret wemo_switch_1
    - !secret wemo_switch_2
    - !secret wemo_switch_3

input_boolean:
  animate_upstairs_lights:
    name: Animate Master Bedroom Lights
    initial: off
  animate_downstairs_lights:
    name: Animate Family Room Lights
    initial: off
  animate_kitchen_lights:
    name: Animate Kitchen Lights
    initial: off
  long_flash:
    name: Long Flash Lights
    initial: off
  short_flash:
    name: Long Flash Lights
    initial: off

automation:
  - alias: Animate Master Bedroom Lights
    initial_state: true
    hide_entity: True
    trigger:
      platform: time
      seconds: '/5'
    condition:
      - condition: state
        entity_id: input_boolean.animate_upstairs_lights
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: group.master_bedroom_lights
          transition: 5
          brightness: 255
          color_temp: 366
        data_template:
          rgb_color: ['{{ "{0:d}".format(range(0, 255)|random) }}' , '{{ "{0:d}".format(range(0, 255)|random) }}', '{{ "{0:d}".format(range(0, 255)|random) }}']
  
  - alias: Restore Masterbedroom Lights
    initial_state: true
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_boolean.animate_upstairs_lights
      to: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: group.master_bedroom_lights
          transition: 5
          rgb_color: [224,175,102]
          brightness: 10
          color_temp: 366
  
  - alias: Animate Familyroom Lights
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      seconds: '/5'
    condition:
      - condition: state
        entity_id: input_boolean.animate_downstairs_lights
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: group.family_room_lights
          transition: 5
          brightness: 255
          color_temp: 366
        data_template:
          rgb_color: ['{{ "{0:d}".format(range(0, 255)|random) }}' , '{{ "{0:d}".format(range(0, 255)|random) }}', '{{ "{0:d}".format(range(0, 255)|random) }}']
          
  - alias: Restore Familyroom Lights
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_boolean.animate_downstairs_lights
      to: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: group.family_room_lights
          transition: 5
          rgb_color: [255, 251, 245]
          brightness: 255
          color_temp: 162
        
  - alias: Animate Kitchen Lights ON
    initial_state: true
    hide_entity: true
    trigger:
      - platform: time
        seconds: '/3'
    condition:
      - condition: state
        entity_id: input_boolean.animate_kitchen_lights
        state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.dinette
        data_template:
          rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
          brightness: 255
          transition: '{{ (range(1, 2)|random) }}'
  
  - alias: Animate Kitchen Lights OFF
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.animate_kitchen_lights
        to: 'off'
    action:
      - service: light.turn_on
        entity_id: light.dinette
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          color_temp: 155
  
  - alias: Long Flash all lights
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.long_flash
        to: 'on'
        from: 'off'
    action:
      - service: light.turn_on
        entity_id:
          - group.all_lights
        data:
          flash: long
      - service: input_boolean.turn_off
        entity_id: input_boolean.long_flash
  
  - alias: Short Flash all_lights
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.short_flash
        to: 'on'
        from: 'off'
    action:
      - service: light.turn_on
        entity_id:
          - group.all_lights
        data:
          flash: short
      - service: input_boolean.turn_off
        entity_id: input_boolean.short_flash

  # - alias: Random Light Effects
    # initial_state: true
    # trigger:
      # - platform: time
        # minutes: '00'
        # seconds: '/15'
    # action:
      # - service: script.turn_on
        # data_template:
          # entity_id: >-
            # {{ [ 'script.start_colorloop',
                 # 'script.stop_colorloop',
                 # 'script.lifx_breathe' ] |random 
            # }}