###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Media Player
#   @description    :   Media Player Sensors, Automations
###############################################################################
homeassistant:
  customize:

# Media Players
    media_player.snapcast_client_b827eb8604f5:
      friendly_name: Front Room Music
    media_player.snapcast_client_b827ebaa08f7:
      friendly_name: Kitchen Music
    media_player.snapcast_client_b827eb011e00:
      friendly_name: TV Room Music
    media_player.snapcast_client_b827eb4445b1:
      friendly_name: Master Bedroom Music
    media_player.snapcast_client_b827eba8e7ef:
      friendly_name: Guest Bedroom 1 Music
    media_player.snapcast_client_b827eb505e2d:
      friendly_name: Guest Bedroom 2 Music
    media_player.snapcast_client_001e8c40c713:
      friendly_name: Basement Music
    media_player.snapcast_client_b827ebf10965:
      friendly_name: Office Room Music
    media_player.snapcast_client_0018e7c4488f:
      friendly_name: HA Server (Basement)

    media_player.mpd:
      friendly_name: Mopidy Media Player
    media_player.gstreamer:
      friendly_name: Gstreamer Media Player
    media_player.sharp_tv:
      friendly_name: Sharp TV
      emulated_hue: true
      emulated_hue_name: TV

group:
  Media Players:
    entities:
      - media_player.gstreamer
      - media_player.mpd
      - media_player.sharp_tv
      - media_player.snapcast_client_0018e7c4488f
      - media_player.snapcast_client_b827eb011e00
      - media_player.snapcast_client_b827eb4445b1
      - media_player.snapcast_client_b827eb505e2d
      - media_player.snapcast_client_b827eb8604f5
      - media_player.snapcast_client_b827eba8e7ef
      - media_player.snapcast_client_b827ebaa08f7
      - media_player.snapcast_client_b827ebf10965
      - media_player.snapcast_group_1d659f9f91c541ba15a4ccb683372d18
      - media_player.snapcast_group_33513078aeaf749d7256aa508c5f3ff7
      - media_player.snapcast_group_53bc45571394eb9060b4cdb29715031d
      - media_player.snapcast_group_80b2566473c8b4128395d562d6760bc2
      - media_player.snapcast_group_81d8ee7df6b354c01ac2b15c412caf31
      - media_player.snapcast_group_9c9ed909371b4cfb3ba5177cbb34f9ea
      - media_player.snapcast_group_be21845f683db25f0db2b35508dccfa3
      - media_player.snapcast_group_d0a7f379181b4d8b72c7c1b6d9c1beb3

media_player:
  - platform: snapcast
    host: !secret snapcast_server_ip

  - platform: mpd
    name: mpd
    host: !secret mopidy_server_ip
    port: !secret mopidy_server_port

# run the following command to link gsp/gi path to HA for Gstreamer to function properly    
# sudo ln -s /usr/lib/python3/dist-packages/gi /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages

  - platform: gstreamer
    pipeline: "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo"

  - platform: sharptv
    host: !secret sharptv_ipaddress
    name: Sharp TV
    port: !secret sharptv_port
    user: !secret sharptv_username
    password: !secret sharptv_password
    power_on_enabled: True
    commands:
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.sharp_tv
          volume_level: ''
    attributes: 
      volume_level: media_player.sharp_tv|volume_level
      source: media_player.sharp_tv|source
      source_list: media_player.sharp_tv|source_list