###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Morning
#   @description    :   Morning routine stuff
###############################################################################
homeassistant:
  customize:
  
    group.travel_time:
      order: 6
      
    # Travel Time
    sensor.home2work:
      friendly_name: Home -> Work
      icon: mdi:domain
    sensor.work2home:
      friendly_name: Work -> Home
      icon: mdi:home
    sensor.suresh2home:
      friendly_name: Suresh -> Home
      icon: mdi:home
    sensor.suresh2work:
      friendly_name: Suresh -> Work
      icon: mdi:domain
    sensor.srinika2home:
      friendly_name: Srinika -> Home
      icon: mdi:home
    sensor.hasika2home:
      friendly_name: Hasika -> Home
      icon: mdi:home

sensor:
  - platform: google_travel_time
    name: Home2Work
    api_key: !secret google_travel_time_apikey 
    origin: zone.home
    destination: zone.work
    options:
      mode: driving
  
  - platform: google_travel_time
    name: Work2Home
    api_key: !secret google_travel_time_apikey 
    origin: zone.work
    destination: zone.home
    options:
      mode: driving
  
  - platform: google_travel_time
    name: Suresh2Home
    api_key: !secret google_travel_time_apikey 
    origin: device_tracker.suresh_suresh
    destination: zone.home
    options:
      mode: driving

  - platform: google_travel_time
    name: Srinika2Home
    api_key: !secret google_travel_time_apikey 
    origin: device_tracker.srinika_srinika
    destination: zone.station
    options:
      mode: driving

  - platform: google_travel_time
    name: Hasika2Home
    api_key: !secret google_travel_time_apikey 
    origin: device_tracker.hasika_hasika
    destination: zone.ade
    options:
      mode: driving

  - platform: google_travel_time
    name: Suresh2Work
    api_key: !secret google_travel_time_apikey 
    origin: device_tracker.suresh_suresh
    destination: zone.work
    options:
      mode: driving
  
group:
  Travel Time:
    entities:
      - sensor.home2work
      - sensor.work2home
      - sensor.suresh2work
      - sensor.suresh2home
      - sensor.srinika2home
      - sensor.hasika2home

automation:
###############################################################################
# Turn Indoor lights ON only during weekdays
###############################################################################
  - alias: Morning Indoor Lights ON
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      minutes: '/5'
      seconds: 00
    condition:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.wakeup_hour.state == now().hour }}'
      - condition: template
        value_template: '{{ states.sensor.wakeup_minute.state == now().minute }}'
    action:
      - service: light.turn_on
        data:
          entity_id: light.dinette
          transition: 15
          brightness: 255
          color_temp: 154
      - service: light.turn_on
        entity_id: light.tradfri_bulb_e26_ws_opal_980lm

###############################################################################
# Turn ON Master Bedroom lights ON in the morning
# Turn On Bedroom Lights 10 minutes after wake up time
###############################################################################
  - alias: Morning Master Bedroom Lights ON (Mallika)
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      minutes: '/5'
      seconds: 00
    condition:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.wakeup_hour.state == now().hour }}'
      - condition: template
        value_template: '{{ now().minute | int == ( states.sensor.wakeup_minute.state | int + 10) }}'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_2
          brightness: 10
          color_temp: 154

  - alias: Morning Master Bedroom Lights OFF (Mallika)
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      minutes: '/5'
      seconds: 00
    condition:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.wakeup_hour.state == now().hour }}'
      - condition: template
        value_template: '{{ now().minute | int == ( states.sensor.wakeup_minute.state | int + 15) }}'
    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_2

###############################################################################
# Turn off outdoor lights 15 minutes after sunrise
###############################################################################
  - alias: Morning Outdoor Lights OFF
    initial_state: true
    hide_entity: true
    trigger:
      platform: sun
      event: sunrise
      offset: '00:15:00'
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.wemofrontporchlightswitch
      - service: switch.turn_off
        data:
          entity_id: switch.wemobackyardlightswitch

###############################################################################
# Turn OF Kitchen Lights after 3 hours of wake up time during school/work days
###############################################################################
  - alias: Morning Kitchen Light OFF
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      minutes: '/5'
      seconds: 00
    condition:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: template
        value_template: '{{ now().hour | int == ( states.sensor.wakeup_hour.state | int + 3) }}'
      - condition: template
        value_template: '{{ states.sensor.wakeup_minute.state == now().minute | int }}'
    action:
     - service: light.turn_off
       data:
         entity_id: light.dinette
     - service: light.turn_off
       data:
         entity_id: light.tradfri_bulb_e26_ws_opal_980lm