###############################################################################
# BUNCH OF MOTION SENSOR RELATED AUTOMATIONS
###############################################################################

automation:

###############################################################################
# Turn ON Kitchen Light when motion detected
###############################################################################
  - alias: Kitchen Light ON When Backdoor Door is Open or Motion Triggered After Sunset
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.back_door_sensor_sensor
          - binary_sensor.kitchen_motion_sensor_sensor
          - binary_sensor.kitchen_multi_sensor_sensor
          - binary_sensor.basement_door_sensor_sensor
          - binary_sensor.motion_sensor_158d0001a662fe
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.dinette
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.dinette
          transition: 3
          brightness: 255

###############################################################################
# If the Kitchen Light is ON between 11 PM and 5 AM, Turn it off after 5 Min.
###############################################################################
  - alias: Late Night Light WatchDog
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - light.dinette
          - light.tradfri_bulb_e26_ws_opal_980lm
          - light.family_room
          - light.master_bedroom
        to: 'on'
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: >
          {% if now().hour | int > 23 or now().hour | int < 5 %}
            true
          {% else %}
            false
          {% endif %}
    action:
      - service: light.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"

  - alias: Family Room Light ON When Motion Detected at Night
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.tv_multi_sensor_sensor
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id: light.family_room
          brightness: 25
          color_temp: 154
          transition: 5