###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   11/19/2017
#   @package        :   Timers and Lights/Switches
#   @description    :   All lights and switches are now timer enabled
#                       and the timer automatically extends when there is 
#                       motion. When timer elapses, it turns off lights.
###############################################################################
homeassistant:
  customize:
    timer.timer_kitchen:
      hidden: true
    timer.timer_familyroom:
      hidden: true
    timer.timer_frontroom:
      hidden: true
    timer.timer_officeroom:
      hidden: true
    timer.timer_garage:
      hidden: true
    timer.timer_diningroom:
      hidden: true
    timer.timer_masterbedroom:
      hidden: true

timer:
  timer_kitchen:
    duration: '00:05:00'
  timer_familyroom:
    duration: '00:05:00'
  timer_frontroom:
    duration: '00:05:00'
  timer_officeroom:
    duration: '00:05:00'
  timer_garage:
    duration: '00:05:00'
  timer_masterbedroom:
    duration: '00:05:00'

automation:

# Front Room:
# Motion Detected - Turn ON the light and extend timer
###############################################################################
  - alias: Frontroom Motion & Timer
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00016db6d2
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id: light.tradfri_bulb_e26_ws_opal_980lm
      - service: timer.start
        entity_id: timer.timer_frontroom

# Front Room:
# Timer Elapsed - Turn OFF lights
###############################################################################
  - alias: Frontroom Timer Elapsed
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: timer.timer_frontroom
        from: 'active'
        to: 'idle'
    action:
      - service: light.turn_off
        entity_id: light.tradfri_bulb_e26_ws_opal_980lm

# Kitchen:
# Motion Detected - Turn ON the light and extend timer
###############################################################################
  - alias: Kitchen Motion & Timer
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001a662fe
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id: light.dinette
        data:
          brightness: 255
          color_temp: 155
      - service: timer.start
        entity_id: timer.timer_kitchen

# Kitchen:
# Timer Elapsed - Turn OFF lights
###############################################################################
  - alias: Kitchen Timer Elapsed
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: timer.timer_kitchen
        from: 'active'
        to: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'        
    action:
      - service_template: >
          {% if now().hour|int >= states.sensor.bedtime_hour.state|int and now().minute|int >= states.sensor.bedtime_minute.state|int %}
            light.turn_off
          {% else %}
            light.turn_on
          {% endif %}
        entity_id: light.dinette
        data:
          brightness: 60

# Family Room: 
# Motion Detected - When TV is OFF, turn ON the light 100% and extend timer
###############################################################################
  - alias: Family Room TV ON Motion & Timer
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: binary_sensor.tv_multi_sensor_sensor
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: or
        conditions:
          - condition: state
            entity_id: media_player.sharp_tv
            state: 'off'
          - condition: state
            entity_id: media_player.sharp_tv
            state: 'unknown'        
    action:
      - service: light.turn_on
        entity_id: light.family_room
        data:
          brightness: 254
          color_temp: 154
          transition: 5          
      - service: timer.start
        entity_id: timer.timer_familyroom

# Family Room:
# Motion Detected - When TV is ON, dim lights to 10%
###############################################################################
  - alias: Family Room TV OFF Motion & Timer
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.tv_multi_sensor_sensor
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: media_player.sharp_tv
        state: 'on'
      - condition: state
        entity_id: light.family_room
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.family_room
          brightness: 10
          color_temp: 154
          transition: 5
      - service: timer.start
        entity_id: timer.timer_familyroom

# Family Room:
# Timer Elapsed - Turn OFF lights
###############################################################################
  - alias: Family Room Timer Elapsed
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: timer.timer_familyroom
        from: 'active'
        to: 'idle'
    action:
      - service: light.turn_off
        entity_id: light.family_room

# Master Bedroom:
# Motion Detected - Turn ON the lights and extend timer
###############################################################################
  - alias: Master Bedroom Motion & Timer
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: binary_sensor.upstairs_multi_sensor_sensor
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_1
          rgb_color: [224,175,102]
          brightness: 10
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_2
          rgb_color: [224,175,102]
          brightness: 10
      - service: timer.start
        entity_id: timer.timer_masterbedroom

# Master Bedroom:
# Timer Elapsed - Turn OFF lights
###############################################################################
  - alias: Master Bedroom Timer Elapsed
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: timer.timer_masterbedroom
        from: 'active'
        to: 'idle'
    action:
      - service: light.turn_off
        entity_id: light.master_bedroom_1
      - service: light.turn_off
        entity_id: light.master_bedroom_2

# Office Room:
# Motion Detected - Turn ON the light and extend timer
###############################################################################
  - alias: Officeroom Motion & Timer
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001a25041
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: switch.turn_on
        entity_id: switch.zwave_smart_switch_switch
      - service: timer.start
        entity_id: timer.timer_officeroom

# Office Room:
# Timer Elapsed - Turn OFF lights
###############################################################################
  - alias: Officeroom Timer Elapsed
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: timer.timer_officeroom
        from: 'active'
        to: 'idle'
    action:
      - service: switch.turn_off
        entity_id: switch.zwave_smart_switch_switch

# Garage:
# Motion Detected - Turn ON the light and extend timer
###############################################################################
  - alias: Garage Motion & Timer
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_motion
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: switch.turn_on
        entity_id: switch.garage_lights
      - service: timer.start
        entity_id: timer.timer_garage

# Garage:
# Timer Elapsed - Turn OFF lights, when "I am not working"
###############################################################################
  - alias: Garage Timer Elapsed
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: timer.timer_garage
        from: 'active'
        to: 'idle'
    condition:
      - condition: state
        entity_id: input_boolean.working_in_garage
        state: 'off'        
    action:
      - service: switch.turn_off
        entity_id: switch.garage_lights
