##################################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   09/15/2017
#   @package        :   Batteries component that uses input Label  
#   @description    :   Owntracks data is now loaded into input_label and totally
#                       simplifies how the battery information is displayed 
##################################################################################
input_label:
  suresh_battery:
    name: Suresh's Battery
  mallika_battery:
    name: Mallika's Battery
  srinika_battery:
    name: Srinika's Battery
  hasika_battery:
    name: Hasika's Battery
  suresh_wifi:
    name: Suresh's iPhone Wifi Enabled?
  mallika_wifi:
    name: Mallika's iPhone Wifi Enabled?
  srinika_wifi:
    name: Srinika's iPhone Wifi Enabled?
  hasika_wifi:
    name: Hasika's iPhone Wifi Enabled?

group:
  New Batteries:
    control: hidden
    entities:
      - input_label.suresh_battery
      - input_label.mallika_battery
      - input_label.srinika_battery
      - input_label.hasika_battery

  New WiFi:
    entities:
      - input_label.suresh_wifi
      - input_label.mallika_wifi
      - input_label.srinika_wifi
      - input_label.hasika_wifi

automation:

  - alias: Refresh OwnTracks Data
    initial_state: true 
    trigger:
      platform: mqtt
      topic: "owntracks/+/+"
    action:
      - service: input_label.set_value
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_wifi"
          value: "{{ 'Yes' if trigger.payload_json.conn == 'w' else 'No' }}"
      - service: input_label.set_icon
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_wifi"
          value: "{{ 'mdi:wifi' if trigger.payload_json.conn == 'w' else 'mdi:wifi-off' }}"
      - service: input_label.set_value
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_battery"
          value: '{{ trigger.payload_json.batt | int }}'
      - service: input_label.set_icon
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_battery"
          value: >
              {% set battery_level = trigger.payload_json.batt | int %}
              {% set battery_round = (battery_level / 10)|int * 10 %}
              {% if trigger.payload_json.charging == 1 %}
                {% if battery_round >= 100 %}
                  mdi:battery-charging-100
                {% elif battery_round > 0 %}
                  mdi:battery-charging-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery
                {% elif battery_round > 0 %}
                  mdi:battery-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}