homeassistant:
  customize:

    group.home__family:
      order: 1

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'settings'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    device_tracker.suresh_suresh:
      friendly_name: Suresh
      entity_picture: /local/suresh.jpg
    device_tracker.mallika_mallika:
      friendly_name: Mallika
      entity_picture: /local/mallika.jpg
    device_tracker.srinika_srinika:
      friendly_name: Srinika
      entity_picture: /local/srinika.jpg
    device_tracker.hasika_hasika:
      friendly_name: Hasika
      entity_picture: /local/hasika.jpg
    device_tracker.ipad_ipad:
      <<: *hidden

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True

group:
  Home & Family:
    entities:
      - device_tracker.suresh_suresh
      - device_tracker.mallika_mallika
      - device_tracker.srinika_srinika
      - device_tracker.hasika_hasika
      - alarm_control_panel.simplisafe