homeassistant:
  customize:
    device_tracker.suresh_suresh:
      friendly_name: Suresh
      entity_picture: /local/suresh.jpg
    device_tracker.mallika_mallika:
      friendly_name: Mallika
      entity_picture: /local/mallika.jpg
    device_tracker.srinika_srinika:
      friendly_name: Srinika
      entity_picture: /local/srinika.jpg
    device_tracker.hasika_hasika:
      friendly_name: Hasika
      entity_picture: /local/hasika.jpg
    device_tracker.ipad_ipad:
      hidden: true

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True 

group:
  Family:
    entities:
      - device_tracker.suresh_suresh
      - device_tracker.mallika_mallika
      - device_tracker.srinika_srinika
      - device_tracker.hasika_hasika
      - automation.alert_when_everyone_is_away
      - automation.welcome_family_owntracks

# automation:
# ###############################################################################
# # Welcome Family Members
# ###############################################################################
  # - alias: Welcome Family OwnTracks
    # initial_state: true
    # hide_entity: true
    # trigger:
      # - platform: state
        # entity_id:
          # - device_tracker.mallika_mallika
          # - device_tracker.suresh_suresh
          # - device_tracker.srinika_srinika
          # - device_tracker.hasika_hasika
        # from: 'not_home'
        # to: 'home'
        # for: '00:02:00'
    # action:
      # - service: script.notify_me
        # data_template:
          # value1: >
            # Welcome home, {{ trigger.entity_id.split('.')[1].split('_')[1] | title }}!
          # value2: ""
      # - service: script.voice_notify
        # data_template:
          # value1: >
            # Welcome home, {{ trigger.entity_id.split('.')[1].split('_')[1] | title }}.

# ###############################################################################
# # Alert when every one is away
# ###############################################################################
  # - alias: Alert when everyone is AWAY
    # initial_state: true
    # hide_entity: true
    # trigger:
      # platform: state
      # entity_id:
        # - device_tracker.mallika_mallika
        # - device_tracker.suresh_suresh
        # - device_tracker.srinika_srinika
        # - device_tracker.hasika_hasika      
      # from: 'home'
      # to: 'not_home'
    # action:
      # - service: script.notify_me
        # data: {"value1":"Warning - No one's at home at the moment.", "value2":""}
