automation:

###############################################################################
# Automation: Provide port on an hourly basis from 8 am to 9 pm
###############################################################################
  - alias: Hourly Report During Day Time
    initial_state: true
    hide_entity: false
    trigger:
      platform: time
      hours: '/01'
      minutes: 05
      seconds: 00
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: template
        value_template: >
          {% set hour = as_timestamp(now()) | timestamp_custom('%-H', true) | int %}
          {% if  hour > 7 and hour < 22 %}
            true
          {% else %}
            false
          {% endif %}
    action:
      - service: script.home_status