homeassistant:
  customize:

    script.start_colorloop:
      friendly_name: Start Colorloop
      icon: mdi:palette
    script.stop_colorloop:
      friendly_name: Stop Colorloop
      icon: mdi:palette
    script.lifx_breathe:
      friendly_name: Lifx Breath
      icon: mdi:lightbulb
    script.owntracks_update:
      friendly_name: OwnTracks Report Location
      icon: mdi:map-marker 

group:
  Scripts:
    control: hidden
    entities:
      - script.home_status
      - script.ifttt_leeo_color_change
      - script.lifx_breathe
      - script.owntracks_update
      - script.restart_hass
      - script.update_hass
      - script.start_colorloop
      - script.stop_colorloop      
      - script.ifttt_notify
      - script.notify_me
      - script.pushbullet_notify
      - script.voice_notify

script:

###############################################################################
# Light Related Scripts
###############################################################################
  start_colorloop:
    sequence:
      - service: light.lifx_effect_colorloop
        data:
          entity_id: light.dinette
          brightness: 255
          period: 2
          spread: 360
          change: 35

  stop_colorloop:
    sequence:
      - service: light.lifx_effect_stop
        data:
          entity_id: light.dinette

  lifx_breathe:
    sequence:
      - service: light.lifx_effect_pulse
        data:
          mode: breathe
          entity_id: light.dinette
          color_name: red
          cycles: 3
          power_on: true

###############################################################################
# Notify Related Scripts
###############################################################################
  ifttt_notify:
    sequence:
      - condition: template
        value_template: '{{ message | trim != "" }}'
      - service: ifttt.trigger
        data_template:
          event: "Smart_Home"
          value1: "{{ message }}"
          value2: ""

  ifttt_leeo_color_change:
    sequence:
      - condition: template
        value_template: '{{ value1 | trim != "" }}'
      - service: ifttt.trigger
        data_template: 
          event: "LEEO_COLOR_CHANGE"
          value1: '{{ value1 }}'

  pushbullet_notify:
    sequence:
      - condition: template
        value_template: '{{ value1 | trim != "" }}' 
      - service: notify.pushbullet
        data_template:
          message: "{{ value1 }}"
          title: "{{ value1 }} {{ value2 }}"

  notify_me:
    sequence:
      - condition: template
        value_template: '{{ message | trim != "" }}'
      - service: script.ifttt_notify
        data_template:
          message: "{{ message }}"

###############################################################################
# Voice Notify
# Conditions:
#   => Only Announce when people are home. Otherwise don't bother!
#   => Only Announce when Music is NOT being played
###############################################################################
  voice_notify:
    sequence:
      - condition: template
        value_template: '{{ states.input_boolean.voice_notifications.state == "on" }}'
      - condition: template
        value_template: '{{ states.input_boolean.do_not_disturb.state | lower == "off" }}'
      - condition: template
        value_template: '{{ states.media_player.gstreamer.state == "idle" }}'
      - condition: template
        value_template: '{{ states.media_player.mpd.state != "playing" }}'
      - condition: template
        value_template: '{{ message | trim != "" }}'
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: template
        value_template: >
          {% if only_at_night | default('no', true ) == "yes" %}
            {% if states.sun.sun.state == "above_horizon" %}
              false
            {% else %}
              true
            {% endif %}
          {% else %}
            true
          {% endif %}
      - service: script.voice_greeting
        data_template:
          greeting: '{{ greeting }}'
      - service: media_player.volume_set
        entity_id: media_player.gstreamer
        data_template:
          volume_level: >
            {% if now().hour | int < 12 and now().hour | int > 6%}
            0.5
            {% elif now().hour|int > 12 and now().hour|int < 20%}
            0.9
            {% else %}
            0.3
            {% endif %}
      - service: tts.amazon_polly_say
        data_template:
          entity_id: media_player.gstreamer
          cache: true
          message: >
            {% set msg = "" %}
            {%- macro getEndGreeting() -%}
              {%- if greeting |default('yes', true ) == "yes" -%}
                Thank you!
              {%- endif -%}
            {%- endmacro -%}
            {% set msg = msg + "<speak> " %}
            {% set msg = msg + ". " + message %}
            {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
            {% set msg = msg + " " + getEndGreeting() %}
            {% set msg = msg + " </speak>" %}
            {{ msg }}

###############################################################################
# Greeting
###############################################################################
  voice_greeting:
    sequence:
      - service: tts.amazon_polly_say
        data_template:
          entity_id: media_player.gstreamer
          cache: true
          message: >
            {% set msg = "" %}
            {% macro getGreeting() %}
              {% if greeting | default('yes', true ) == "yes" %}
                {% if now().hour|int < 12 %}
                  Good morning.
                {% elif now().hour|int < 18 %}
                  Good afternoon.
                {% else %}
                  Good evening.
                {% endif %}
              {% endif %}
            {% endmacro %}
            {% set msg = msg + "<speak> " %}
            {% set msg = msg + " " + getGreeting() %}
            {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
            {% set msg = msg + " </speak>" %}
            {{ msg }}

###############################################################################
# Status around the house
###############################################################################
  home_status:
    sequence:
      - service: script.voice_notify
        data_template:
          message: !include ../templates/home_status.yaml