homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'settings'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    group.control_panel:
      <<: *not_exposed

    input_boolean.working_in_garage:
      friendly_name: Working in Garage
      icon: mdi:worker
    input_boolean.voice_notifications:
      <<: *exposed
      icon: mdi:microphone-off
      emulated_hue_name: Home Assistant Announcements
      homebridge_name: Home Assistant Announcements
    input_boolean.do_not_disturb:
      <<: *exposed
      homebridge_name: Do Not Disturb
    input_boolean.home_security:
      <<: *exposed
      homebridge_name: Turn ON Home Security
    input_boolean.home_assistant_restart:
      <<: *exposed
      homebridge_name: Restart Home Assistant
    input_boolean.home_assistant_status:
      <<: *exposed
      homebridge_name: Home Status
    input_boolean.alarm_clock:
      <<: *exposed
      homebridge_name: Alarm Clock
    input_boolean.fix_tv:
      <<: *exposed
      homebridge_name: Fix TV

group:
  Control Panel:
    control: hidden
    entities:
      - input_boolean.voice_notifications
      - input_boolean.do_not_disturb
      - input_boolean.home_security
      - input_boolean.home_assistant_restart
      - input_boolean.home_assistant_update
      - input_boolean.home_assistant_status
      - input_boolean.notify_motion_pictures
      - input_boolean.working_in_garage
      - input_boolean.hourly_reports
      - input_boolean.welcome_family_announcement
      - input_boolean.trash_reminders
      - input_boolean.enjoyable_weather_reminders
      - input_boolean.alert_when_someone_enters_zone
      - input_boolean.alert_when_someone_leaves_zone
      - input_boolean.alarm_clock
      - input_boolean.fix_tv

# Input Booleans
###############################################################################

input_boolean:
  voice_notifications:
    name: Home Assistant Announcements
    initial: on
    icon: mdi:volume-off

  do_not_disturb:
    name: Do Not Disturb
    initial: off
    icon: mdi:do-not-disturb

  home_security:
    name: Home Security System
    initial: off
    icon: mdi:verified

  home_assistant_restart:
    name: Home Assistant
    initial: off
    icon: mdi:home-assistant

  home_assistant_update:
    name: Latest Version Of Home Assistant
    initial: off
    icon: mdi:home-assistant

  home_assistant_status:
    name: Home Status
    initial: off
    icon: mdi:home-assistant

  working_in_garage:
    name: Working in Garage
    initial: off
    icon: mdi:worker

  hourly_reports:
    name: Hourly Report
    initial: on
    icon: mdi:file-chart

  notify_motion_pictures:
    name: Notify With Pictures (Motion)
    initial: off
    icon: mdi:camera

  welcome_family_announcement:
    name: Welcome Family Member Announcements
    initial: on
    icon: mdi:home

  # clear_tts_cache:
  #   name: Clear TTS Cache Daily
  #   initial: on
  #   icon: mdi:text-to-speech

  trash_reminders:
    name: Remind Trash Notifications
    initial: on
    icon: mdi:recycle

  enjoyable_weather_reminders:
    name: Remind me to enjoy Good Weather
    initial: on
    icon: mdi:weather-sunny

  notify_security_system_changes:
    name: Notify Security System Status Change
    initial: on
    icon: mdi:verified

  alert_no_one_home:
    name: Alert When No One Home
    initial: on
    icon: mdi:alert

  alert_when_someone_enters_zone:
    name: Alert When Someone Enters A Zone
    initial: on
    icon: mdi:map-marker

  alert_when_someone_leaves_zone:
    name: Alert When Someone Leaves A Zone
    initial: on
    icon: mdi:map-marker

  alarm_clock:
    name: Alarm Clock
    initial: on
    icon: mdi:calendar-check

  fix_tv:
    name: Fix TV
    initial: off
    icon: mdi:television

# Automations
###############################################################################

automation:

  - alias: Fix TV
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.fix_tv
        to: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.wemoswitch1
      - delay: '00:00:05'
      - service: switch.turn_on
        entity_id: switch.wemoswitch1
      - service: input_boolean.turn_off
        entity_id: input_boolean.fix_tv

# Do not disturb for 2 hours
# Simply turns ON the Do Not Disturb Flag ad resets 
# after 2 hours. The Do Not Disturb flag is used in
# voice_notify script
######################################################
  - alias: Do Not Disturb For 2 hours
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.do_not_disturb
        to: 'on'
        for:
          hours: 2
          minutes: 0
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.do_not_disturb

# Turn ON Home Security System - only if it is not ON
######################################################
  - alias: Home Security ON
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_security
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ states.alarm_control_panel.simplisafe.state == "disarmed" }}'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.simplisafe
      - delay:
          minutes: 0
          seconds: 10
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_security

# Announces "Status" in the house
######################################################
  - alias: Home Status ON
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_status
        to: 'on'
    action:
      - service: script.home_status
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_assistant_status

# Restarts Home Assistant at Alexa's Command
######################################################
  - alias: Restart Home Assistant
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_restart
        to: 'on'
    action:
      - service: script.restart_hass
        
# Updates Home Assistant at Alexa's Command
######################################################
  - alias: Update Home Assistant
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_update
        to: 'on'
    action:
      - service: script.update_hass
      - delay:
          minutes: 0
          seconds: 10
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_assistant_update

# Hourly Reports
######################################################
  - alias: Hourly Report During Day Time
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      hours: '/01'
      minutes: 05
      seconds: 00
    condition:
      - condition: template
        value_template: '{{ states.input_boolean.hourly_reports.state == "on" }}'
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: template
        value_template: >
          {% set hour = now().hour | int %}
          {% if  hour > 7 and hour < 21 %}
            true
          {% else %}
            false
          {% endif %}
    action:
      - service: script.home_status

# # Clear TTS Cache Daily
# ######################################################
#   - alias: Clear TTS Cache
#     initial_state: true
#     hide_entity: true
#     trigger:
#       platform: time
#       at: '4:45:00'
#     condition:
#       - condition: template
#         value_template: '{{ states.input_boolean.clear_tts_cache.state == "on" }}'
#     action:
#       service: tts.clear_cache
