homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'settings'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    group.control_panel:
      <<: *not_exposed

    input_boolean.working_in_garage:
      friendly_name: Working in Garage
      icon: mdi:worker
    input_boolean.mute_voice_notifications:
      <<: *exposed
      icon: mdi:microphone-off
    input_boolean.do_not_disturb:
      <<: *exposed
    input_boolean.home_security:
      <<: *exposed
    input_boolean.home_assistant_restart:
      <<: *exposed
    input_boolean.home_assistant_status:
      <<: *exposed

group:
  Control Panel:
    entities:
      - input_boolean.mute_voice_notifications
      - input_boolean.do_not_disturb
      - input_boolean.home_security
      - input_boolean.home_assistant_restart
      - input_boolean.home_assistant_update
      - input_boolean.home_assistant_status
      - input_boolean.notify_motion_pictures
      - input_boolean.working_in_garage
      - input_boolean.hourly_reports
      - input_boolean.welcome_family_announcement
      - input_boolean.clear_tts_cache
      - input_boolean.trash_reminders
      - input_boolean.enjoyable_weather_reminders

# Input Booleans
###############################################################################

input_boolean:
  mute_voice_notifications:
    name: Mute Voice Notifications
    initial: off

  do_not_disturb:
    name: Do Not Disturb
    initial: off
    icon: mdi:do-not-disturb

  home_security:
    name: Home Security System
    initial: off

  home_assistant_restart:
    name: Home Assistant
    initial: off

  home_assistant_update:
    name: Latest Version Of Home Assistant
    initial: off

  home_assistant_status:
    name: Home Status
    initial: off    

  working_in_garage:
    name: Working in Garage
    initial: off

  hourly_reports:
    name: Hourly Report
    initial: on

  notify_motion_pictures:
    name: Notify With Pictures (Motion)
    initial: off

  welcome_family_announcement:
    name: Welcome Family Member Announcements
    initial: on

  clear_tts_cache:
    name: Clear TTS Cache Daily
    initial: on

  trash_reminders:
    name: Remind Trash Notifications
    initial: on
    icon: mdi:recycle

  enjoyable_weather_reminders:
    name: Remind me to enjoy Good Weather
    initial: on
    icon: mdi:recycle

# Automations
###############################################################################

automation:

# Do not disturb for 2 hours
# Simply turns ON the Do Not Disturb Flag ad resets 
# after 2 hours. The Do Not Disturb flag is used in
# voice_notify script
######################################################
  - alias: Do Not Disturb For 2 hours
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.do_not_disturb
        to: 'on'
        for:
          hours: 2
          minutes: 0
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.do_not_disturb

# Turn ON Home Security System - only if it is not ON
######################################################
  - alias: Home Security ON
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_security
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ states.alarm_control_panel.simplisafe.state == "disarmed" }}'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.simplisafe
      - delay:
          minutes: 0
          seconds: 10
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_security

# Announces "Status" in the house
######################################################
  - alias: Home Status ON
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_status
        to: 'on'
    action:
      - service: script.home_status
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_assistant_status

# Restarts Home Assistant at Alexa's Command
######################################################
  - alias: Restart Home Assistant
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_restart
        to: 'on'
    action:
      - service: script.restart_hass
        
# Updates Home Assistant at Alexa's Command
######################################################
  - alias: Update Home Assistant
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_update
        to: 'on'
    action:
      - service: script.update_hass
      - delay:
          minutes: 0
          seconds: 10
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_assistant_update

# Hourly Reports
######################################################
  - alias: Hourly Report During Day Time
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      hours: '/01'
      minutes: 05
      seconds: 00
    condition:
      - condition: template
        value_template: '{{ states.input_boolean.hourly_reports.state == "on" }}'
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: template
        value_template: >
          {% set hour = as_timestamp(now()) | timestamp_custom('%-H', true) | int %}
          {% if  hour > 7 and hour < 21 %}
            true
          {% else %}
            false
          {% endif %}
    action:
      - service: script.home_status

# Clear TTS Cache Daily
######################################################
  - alias: Clear TTS Cache
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      at: '4:45:00'
    condition:
      - condition: template
        value_template: '{{ states.input_boolean.clear_tts_cache.state == "on" }}'
    action:
      service: tts.clear_cache