# automation:

  # - alias: Test State Changed Event
  #   trigger:
  #     - platform: event
  #       event_type: state_changed
  
  #   action:
  #     - service: mqtt.publish
  #       data_template:
  #         topic: "/homeassistant/event"
  #         retain: false
  #         payload: "{{ trigger.event.data.entity_id }}"
  
  # - alias: Test Platform Changed Event
  #   trigger:
  #     - platform: event
  #       event_type: platform_discovered
    
  #   action:
  #     - service: mqtt.publish
  #       data_template:
  #         topic: "/homeassistant/platform"
  #         retain: false
  #         payload: >
  #           {{ trigger.event.data.service }} - {{ trigger.event.data.discovered }}
  
  sensor:
  - platform: rest
    resource: https://launchlibrary.net/1.2.2/launch/next/10
    name: Rocket
    value_template: >-
      {% set is_rocket_day = False %}
      {% for day_val in value_json.launches -%}
        {% set today_date = now().strftime('%B %d') %}
        {% set target_date = day_val.net.split(',')[0] %}
        {% if today_date == target_date  and day_val.location.id | int == 16 %}
            {% set is_rocket_day = True %}
        {% endif %}
      {% endfor %}
      {{ is_rocket_day }}

sensor:
  - platform: rest
    resource: https://launchlibrary.net/1.2.2/launch/next/10
    name: Rocket
    value_template: >-
      {% set rocket_launch_datetime = "" %}
      {% for day_val in value_json.launches -%}
    	{% set today_date = now().strftime('%B %d') %}
    	{% set target_date = day_val.net.split(',')[0] %}
    	{% if today_date == target_date and day_val.location.id | int == 16 %}
    	    {% set rocket_launch_datetime = day_val.windowstart.split(' ')[3] %}
    	{% endif %}
      {% endfor %}
      {{ rocket_launch_datetime }}
