###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   11/07/2017
#   @package        :   Work From Home
#   @description    :   Reminds me to Get Up and Walk around the house every 
#                       30 minutes. 
###############################################################################
homeassistant:
  customize:
    timer.getup_timer:
      hidden: true

input_boolean:
  work_from_home:
    name: Work From Home
    initial: off
    icon: mdi:work

timer:
  getup_timer:
    duration: '00:30:00'

automation:

# Turn ON Working From Home if it detects you are still HOME during weekdays 
# after 10 AM
###############################################################################
  - alias: WFH Sensor Update
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      - condition: template
        value_template: '{{ states.binary_sensor.workday_sensor.state == "on" }}'
    action:
      - service_template: >
          {% if states.device_tracker.suresh_suresh.state == "home" %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.work_from_home
      - service: timer.start
        entity_id: timer.getup_timer

# Left home... or it is 5PM... turn off the timer! 
###############################################################################
  - alias: Suresh came home between 10am and 5pm
    trigger:
      - platform: state
        entity_id: device_tracker.suresh_suresh
        to: 'not_home'
      - platform: time
        at: '17:00:00'
    condition:
      - condition: template
        value_template: '{{ now().hour | int > 10 and now().hour | int < 17 }}'
    action:
      - service: timer.cancel
        entity_id: timer.getup_timer

# Timer completed... time to announce, so that I get up and take a walk around
###############################################################################
  - alias: Getup & Walk Timer Completed
    trigger:
      - platform: state
        entity_id: timer.getup_timer
        from: 'active'
        to: 'idle'
    condition:
      - condition: template
        value_template: '{{ states.device_tracker.suresh_suresh.state == "home" }}'
      - condition: template
        value_template: '{{ states.binary_sensor.workday_sensor.state == "on" }}'
      - condition: template
        value_template: '{{ states.input_boolean.work_from_home.state == "on" }}'
    action:
      - service: script.voice_notify
        data_template:
          message: "It is time to stand up and walk around!"
      - service: timer.start
        entity_id: timer.getup_timer