input_label:
  aeotec_water_sensor:
  audio_detector:
  back_door_sensor:
  basement_door_sensor:
  downstairs_multi_sensor:
  front_door_sensor:
  front_room_multi_sensor:
  front_room_window_sensor:
  garage_door_sensor:
  guest_bedroom_multi_sensor:
  hallway_light_switch:
  kitchen_motion_sensor:
  single_car_garage_door_tilt_sensor:
  stairs_motion_sensor:
  tv_multi_sensor:
  two_car_garage_door_tilt_sensor:
  upstairs_multi_sensor:
  wallmote:

group:
  ZWave Batteries:
    entities:
      - input_label.aeotec_water_sensor
      - input_label.audio_detector
      - input_label.back_door_sensor
      - input_label.basement_door_sensor
      - input_label.downstairs_multi_sensor
      - input_label.front_door_sensor
      - input_label.front_room_multi_sensor
      - input_label.front_room_window_sensor
      - input_label.garage_door_sensor
      - input_label.guest_bedroom_multi_sensor
      - input_label.hallway_light_switch
      - input_label.kitchen_motion_sensor
      - input_label.single_car_garage_door_tilt_sensor
      - input_label.stairs_motion_sensor
      - input_label.tv_multi_sensor
      - input_label.two_car_garage_door_tilt_sensor
      - input_label.upstairs_multi_sensor
      - input_label.wallmote

automation:
  - alias: Update ZWave Battery Levels
    trigger:
      - platform: event
        event_type: state_changed
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.entity_id is not none }}"
      - condition: template
        value_template: "{{ trigger.event.data.entity_id.split('.')[0] == 'zwave' }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.attributes is not none }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.attributes.battery_level | trim != '' }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.attributes.battery_level | default(999) | int != 999 }}"
    action:
      - service: input_label.set_value
        data_template:
          entity_id: "input_label.{{- trigger.event.data.entity_id.split('.')[1] -}}"
          value: "{{ trigger.event.data.new_state.attributes.battery_level }}"
      - service: input_label.set_name
        data_template:
          entity_id: "input_label.{{- trigger.event.data.entity_id.split('.')[1] -}}"
          value: "{{ trigger.event.data.new_state.attributes.friendly_name }}'s Battery"
      - service: input_label.set_icon
        data_template:
          entity_id: "input_label.{{- trigger.event.data.entity_id.split('.')[1] -}}"
          value: >
            {% set battery_level = trigger.event.data.new_state.attributes.battery_level | int %}
            {% set battery_round = (battery_level / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}