###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Z-Wave package
#   @description    :   Z-Wave Still and it's configuration stuff
###############################################################################
homeassistant:
  customize:

    group.zwave_devices:
      order: 97

# Z-Wave Device(s)
    zwave.aeotec_zw090_zstick_gen5_1:
      hidden: False
      friendly_name: The Aeotec Z-Wave Stick

zwave:
  usb_path: /dev/ttyACM0

group:

  ZWave Devices:
    entities:
      - zwave.aeotec_zw074_multisensor_gen5_2
      - zwave.two_car_garage_door_tilt_sensor
      - zwave.single_car_garage_door_tilt_sensor
      - automation.heal_zwave_network

  Multi Sensors:
    entities:
      - zwave.aeotec_zw074_multisensor_gen5
      - zwave.aeotec_zw074_multisensor_gen5_2
      - zwave.aeotec_zw090_zstick_gen5
      - zwave.aeotec_zw100_multisensor_6
      - zwave.ecolink_door_sensor
      - zwave.ecolink_door_sensor_2
      - zwave.ecolink_garage_door_tilt_sensor
      - zwave.ecolink_garage_door_tilt_sensor_2
      
  Binary Sensors:
    entities:
      - binary_sensor.aeotec_zw074_multisensor_gen5_sensor
      - binary_sensor.aeotec_zw074_multisensor_gen5_sensor_2
      - binary_sensor.aeotec_zw100_multisensor_6_sensor
      - binary_sensor.ecolink_door_sensor_sensor
      - binary_sensor.ecolink_door_sensor_sensor_2
      - binary_sensor.kids_room_occupancy
      - binary_sensor.workday_sensor

  ZWave Sensors:
    entities:
      - sensor.aeotec_zw074_multisensor_gen5_alarm_level
      - sensor.aeotec_zw074_multisensor_gen5_alarm_level_2
      - sensor.aeotec_zw074_multisensor_gen5_alarm_type
      - sensor.aeotec_zw074_multisensor_gen5_alarm_type_2
      - sensor.aeotec_zw074_multisensor_gen5_burglar
      - sensor.aeotec_zw074_multisensor_gen5_burglar_2
      - sensor.aeotec_zw074_multisensor_gen5_luminance
      - sensor.aeotec_zw074_multisensor_gen5_luminance_2
      - sensor.aeotec_zw074_multisensor_gen5_relative_humidity
      - sensor.aeotec_zw074_multisensor_gen5_relative_humidity_2
      - sensor.aeotec_zw074_multisensor_gen5_sourcenodeid
      - sensor.aeotec_zw074_multisensor_gen5_sourcenodeid_2
      - sensor.aeotec_zw074_multisensor_gen5_temperature
      - sensor.aeotec_zw074_multisensor_gen5_temperature_2
      - sensor.aeotec_zw100_multisensor_6_alarm_level
      - sensor.aeotec_zw100_multisensor_6_alarm_type
      - sensor.aeotec_zw100_multisensor_6_burglar
      - sensor.aeotec_zw100_multisensor_6_luminance
      - sensor.aeotec_zw100_multisensor_6_relative_humidity
      - sensor.aeotec_zw100_multisensor_6_sourcenodeid
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.aeotec_zw100_multisensor_6_ultraviolet
      - sensor.ecolink_door_sensor_access_control
      - sensor.ecolink_door_sensor_access_control_2
      - sensor.ecolink_door_sensor_alarm_level
      - sensor.ecolink_door_sensor_alarm_level_2
      - sensor.ecolink_door_sensor_alarm_type
      - sensor.ecolink_door_sensor_alarm_type_2
      - sensor.ecolink_door_sensor_burglar
      - sensor.ecolink_door_sensor_burglar_2
      - sensor.ecolink_door_sensor_power_management
      - sensor.ecolink_door_sensor_power_management_2
      - sensor.ecolink_door_sensor_sourcenodeid
      - sensor.ecolink_door_sensor_sourcenodeid_2
      - sensor.two_car_garage_door_sensor_battery
      - sensor.two_car_garage_door_sensor_status
      - sensor.two_car_garage_door_tilt_sensor_access_control
      - sensor.two_car_garage_door_tilt_sensor_alarm_level
      - sensor.two_car_garage_door_tilt_sensor_alarm_type
      - sensor.two_car_garage_door_tilt_sensor_burglar
      - sensor.two_car_garage_door_tilt_sensor_power_management
      - sensor.two_car_garage_door_tilt_sensor_sourcenodeid
      - sensor.single_car_garage_door_sensor_battery
      - sensor.single_car_garage_door_sensor_status
      - sensor.single_car_garage_door_tilt_sensor_access_control
      - sensor.single_car_garage_door_tilt_sensor_alarm_level
      - sensor.single_car_garage_door_tilt_sensor_alarm_type
      - sensor.single_car_garage_door_tilt_sensor_burglar
      - sensor.single_car_garage_door_tilt_sensor_power_management
      - sensor.single_car_garage_door_tilt_sensor_sourcenodeid
      - switch.single_car_garage

automation:
  - alias: Heal Z-Wave Network
    initial_state: true
    trigger:
      platform: time
      at: '4:30:00'
    action:
      service: zwave.heal_network
