homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'batteries'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

      not_hidden: &not_hidden
        <<: *customize
        hidden: false
        critical: true

group:
  ZWave Batteries:
    entities:
      - sensor.audio_detector_battery
      - sensor.back_door_sensor_battery
      - sensor.basement_door_sensor_battery
      - sensor.downstairs_multi_sensor_battery
      - sensor.family_room_multi_sensor_battery
      - sensor.front_door_sensor_battery
      - sensor.front_room_multi_sensor_battery
      - sensor.garage_door_sensor_battery
      - sensor.hallway_light_switch_battery
      - sensor.kitchen_motion_sensor_battery
      - sensor.master_bedroom_multi_sensor_battery
      - sensor.single_car_garage_door_tilt_sensor_battery
      - sensor.stairs_motion_sensor_battery
      - sensor.two_car_garage_door_tilt_sensor_battery
      - sensor.upstairs_multi_sensor_battery
      - sensor.wallmote_battery

sensor:

  - platform: template
    sensors:
      single_car_garage_door_sensor_battery:
        value_template: "{{ (states.zwave.single_car_garage_door_tilt_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Single Car Garage Door Sensor Battery
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.single_car_garage_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      two_car_garage_door_sensor_battery:
        value_template: "{{ (states.zwave.two_car_garage_door_tilt_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Double Car Garage Door Sensor Battery
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.two_car_garage_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      back_door_sensor_battery:
        value_template: "{{ (states.zwave.back_door_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Back Door Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.back_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      basement_door_sensor_battery:
        value_template: "{{ (states.zwave.basement_door_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Basement Door Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.basement_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      downstairs_multi_sensor_battery:
        value_template: "{{ (states.zwave.downstairs_multi_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Downstairs Multi Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.downstairs_multi_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      family_room_multi_sensor_battery:
        value_template: "{{ (states.zwave.family_room_multi_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Family Room Multi Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.family_room_multi_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      front_door_sensor_battery:
        value_template: "{{ (states.zwave.front_door_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Front Door Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.front_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      front_room_multi_sensor_battery:
        value_template: "{{ (states.zwave.front_room_multi_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Front Room Multi Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.front_room_multi_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      garage_door_sensor_battery:
        value_template: "{{ (states.zwave.garage_door_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Garage Door Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.garage_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}


  - platform: template
    sensors:
      hallway_light_switch_battery:
        value_template: "{{ (states.zwave.hallway_light_switch.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Hallway Light Switch
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.hallway_light_switch_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      kitchen_motion_sensor_battery:
        value_template: "{{ (states.zwave.kitchen_motion_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Kitchen Motion Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.kitchen_motion_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      master_bedroom_multi_sensor_battery:
        value_template: "{{ (states.zwave.master_bedroom_multi_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Master Bedroom Multi Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.master_bedroom_multi_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      stairs_motion_sensor_battery:
        value_template: "{{ (states.zwave.stairs_motion_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Stairs Motion Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.stairs_motion_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      upstairs_multi_sensor_battery:
        value_template: "{{ (states.zwave.upstairs_multi_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Upstairs Multi Sensor
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.upstairs_multi_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      wallmote_battery:
        value_template: "{{ (states.zwave.wallmote.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Wall Mote
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.wallmote_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}