###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Z-Wave package
#   @description    :   Z-Wave Still and it's configuration stuff
###############################################################################
homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'settings'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

# By default all the aeotec stuff is hidden, unhide the stuff that you want
    sensor.aeotec_zw100_multisensor_6_luminance:
      friendly_name: Front Room Luminance
      hidden: False
    sensor.aeotec_zw074_multisensor_gen5_luminance:
      friendly_name: Upstairs Luminance
      hidden: False
    sensor.aeotec_zw074_multisensor_gen5_luminance_2:
      friendly_name: TV Room Luminance
      hidden: False
    sensor.aeotec_zw100_multisensor_6_relative_humidity:
      friendly_name: Front Room Humidity
      hidden: False
    sensor.aeotec_zw074_multisensor_gen5_relative_humidity:
      friendly_name: Upstairs Humidity
      hidden: False
    sensor.aeotec_zw074_multisensor_gen5_relative_humidity_2:
      friendly_name: TV Room Humidity
      hidden: False
    sensor.aeotec_zw100_multisensor_6_temperature:
      friendly_name: Front Room Humidity
      hidden: False
    sensor.aeotec_zw074_multisensor_gen5_temperature:
      friendly_name: Upstairs Temperature
      hidden: False
    sensor.aeotec_zw074_multisensor_gen5_temperature_2:
      friendly_name: TV Room Temperature
      hidden: False

    group.1_car_garage:
      <<: *hidden
    group.2_car_garage:
      <<: *hidden
    group.zwave_sensors:
      <<: *hidden
    group.multi_sensors:
      <<: *hidden
    group.front_room:
      <<: *hidden
    group.tv_room:
      <<: *hidden
    group.upstairs:
      <<: *hidden
    group.zwave_devices:
      <<: *hidden

    zwave.aeotec_zw090_zstick_gen5_1:
      hidden: False
      friendly_name: The Aeotec Z-Wave Stick

zwave:
  usb_path: /dev/ttyACM0

group:

  ZWave Devices:
    entities:
      - zwave.aeotec_zw074_multisensor_gen5_2
      - zwave.two_car_garage_door_tilt_sensor
      - zwave.single_car_garage_door_tilt_sensor

  Multi Sensors:
    entities:
      - zwave.aeotec_zw074_multisensor_gen5
      - zwave.aeotec_zw074_multisensor_gen5_2
      - zwave.aeotec_zw090_zstick_gen5
      - zwave.aeotec_zw100_multisensor_6
      - zwave.ecolink_door_sensor
      - zwave.ecolink_door_sensor_2
      - zwave.ecolink_garage_door_tilt_sensor
      - zwave.ecolink_garage_door_tilt_sensor_2
      
  Upstairs:
    entities:
      - sensor.aeotec_zw074_multisensor_gen5_alarm_level_2
      - sensor.aeotec_zw074_multisensor_gen5_alarm_type_2
      - sensor.aeotec_zw074_multisensor_gen5_burglar_2
      - sensor.aeotec_zw074_multisensor_gen5_sourcenodeid_2

  TV Room:
    entities:
      - sensor.aeotec_zw074_multisensor_gen5_alarm_level
      - sensor.aeotec_zw074_multisensor_gen5_alarm_type
      - sensor.aeotec_zw074_multisensor_gen5_burglar
      - sensor.aeotec_zw074_multisensor_gen5_sourcenodeid
      - sensor.aeotec_zw074_multisensor_gen5_power

  Front Room:
    entities:
      - sensor.aeotec_zw100_multisensor_6_alarm_level
      - sensor.aeotec_zw100_multisensor_6_alarm_type
      - sensor.aeotec_zw100_multisensor_6_burglar
      - sensor.aeotec_zw100_multisensor_6_sourcenodeid
      - sensor.aeotec_zw100_multisensor_6_ultraviolet

  ZWave Sensors:
    entities:
      - sensor.ecolink_door_sensor_access_control
      - sensor.ecolink_door_sensor_access_control_2
      - sensor.ecolink_door_sensor_alarm_level
      - sensor.ecolink_door_sensor_alarm_level_2
      - sensor.ecolink_door_sensor_alarm_type
      - sensor.ecolink_door_sensor_alarm_type_2
      - sensor.ecolink_door_sensor_burglar
      - sensor.ecolink_door_sensor_burglar_2
      - sensor.ecolink_door_sensor_power_management
      - sensor.ecolink_door_sensor_power_management_2
      - sensor.ecolink_door_sensor_sourcenodeid
      - sensor.ecolink_door_sensor_sourcenodeid_2

  2 Car Garage:
    entities:
      - sensor.two_car_garage_door_sensor_battery
      - sensor.two_car_garage_door_sensor_status
      - sensor.two_car_garage_door_tilt_sensor_access_control
      - sensor.two_car_garage_door_tilt_sensor_alarm_level
      - sensor.two_car_garage_door_tilt_sensor_alarm_type
      - sensor.two_car_garage_door_tilt_sensor_burglar
      - sensor.two_car_garage_door_tilt_sensor_power_management
      - sensor.two_car_garage_door_tilt_sensor_sourcenodeid

  1 Car Garage:
    entities:
      - sensor.single_car_garage_door_sensor_battery
      - sensor.single_car_garage_door_sensor_status
      - sensor.single_car_garage_door_tilt_sensor_access_control
      - sensor.single_car_garage_door_tilt_sensor_alarm_level
      - sensor.single_car_garage_door_tilt_sensor_alarm_type
      - sensor.single_car_garage_door_tilt_sensor_burglar
      - sensor.single_car_garage_door_tilt_sensor_power_management
      - sensor.single_car_garage_door_tilt_sensor_sourcenodeid
      - switch.single_car_garage

  Door Sensors:
      - binary_sensor.ecolink_door_sensor_sensor
      - binary_sensor.ecolink_door_sensor_sensor_2

  Motion Sensors:
    entities:
      - binary_sensor.aeotec_zw074_multisensor_gen5_sensor
      - binary_sensor.aeotec_zw074_multisensor_gen5_sensor_2
      - binary_sensor.aeotec_zw100_multisensor_6_sensor
      - binary_sensor.kids_room_occupancy
      - binary_sensor.downstairs_occupancy

  Light Levels:
    entities:
      - sensor.aeotec_zw100_multisensor_6_luminance
      - sensor.aeotec_zw074_multisensor_gen5_luminance
      - sensor.aeotec_zw074_multisensor_gen5_luminance_2

  Humidity Levels:
    entities:
      - sensor.aeotec_zw100_multisensor_6_relative_humidity
      - sensor.aeotec_zw074_multisensor_gen5_relative_humidity
      - sensor.aeotec_zw074_multisensor_gen5_relative_humidity_2

  Temperature Levels:
    entities:
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.aeotec_zw074_multisensor_gen5_temperature
      - sensor.aeotec_zw074_multisensor_gen5_temperature_2